// Native tree dimensions and measured root pivots. Generated by pack-river-trees.mjs.
export const RIVER_TREE_ART={
  "river-tree-oak": {
    "width": 1222,
    "height": 1287,
    "rootX": 0.5540098199672667,
    "rootLeft": 0.19967266775777415,
    "rootRight": 0.9083469721767594
  },
  "river-tree-willow": {
    "width": 1175,
    "height": 1324,
    "rootX": 0.6025531914893617,
    "rootLeft": 0.3446808510638298,
    "rootRight": 0.8604255319148936
  },
  "river-tree-birch": {
    "width": 965,
    "height": 1516,
    "rootX": 0.572020725388601,
    "rootLeft": 0.20932642487046632,
    "rootRight": 0.9347150259067357
  },
  "river-tree-hawthorn": {
    "width": 1488,
    "height": 1024,
    "rootX": 0.2536962365591398,
    "rootLeft": 0.006720430107526882,
    "rootRight": 0.5006720430107527
  }
};
